language: java
script:
- chmod 777 ./src/test/resources/HIS_E2/app_sanidad/geckodriver
- mvn test
dist: xenial
services:
  - xvfb
addons:
  firefox: "70.0"
notifications:
  slack: hisespacio:0qEQjO7RRhAMmk67zdatTrtr
deploy:
    provider: heroku
    api_key:
        secure: 9416fe1c-ba23-4f9b-80fe-8e4973afbdc1
    app: esanidad
